Type.registerNamespace('DesignSpace');DesignSpace.Canvas=function(){}
DesignSpace.Canvas.prototype={init:function(){DesignSpace.Lib._Worker.$B();DesignSpace.Lib._Worker.$19();}}
Type.registerNamespace('DesignerSpace.Lib');DesignerSpace.Lib.Events=function(){}
DesignerSpace.Lib.Util=function(){}
DesignerSpace.Lib.Util.isChecked=function(Id){if(document.getElementById(Id)==null){return false;}return document.getElementById(Id).checked;}
DesignerSpace.Lib.Util.getValue=function(Id){if(document.getElementById(Id)==null){return '';}return document.getElementById(Id).value.toString();}
DesignerSpace.Lib.Util.setChecked=function(Id){if(document.getElementById(Id)==null){return;}document.getElementById ( Id).checked=true;}
DesignerSpace.Lib.Util.$0=function($p0){if(document.getElementById($p0)==null){return;}document.getElementById($p0).setAttribute('disabled','disabled');}
DesignerSpace.Lib.Util.$1=function($p0){if(document.getElementById($p0)==null){return;}document.getElementById($p0).removeAttribute('disabled');}
DesignerSpace.Lib.Util.setValue=function(Id,D){if(document.getElementById(Id)==null){return;}document.getElementById ( Id).value=D;}
DesignerSpace.Lib.Util.addOptionItem=function(Name,Value,isGroup){var $0=window.document.createElement((isGroup)?'optgroup':'option');if(!isGroup){$0.innerHTML=Name;}$0.setAttribute((isGroup)?'label':'value',Value);return $0;}
DesignerSpace.Lib.Util.setOption=function(id,value){var $0=document.getElementById(id);for(var $1=0;$1<$0.children.length;$1++){var $2=$0.children[$1];if($2.tagName.toLowerCase()==='optgroup'){for(var $3=0;$3<$2.children.length;$3++){var $4=$2.children[$3];if(O.value===value){$4.setAttribute('selected','selected');O.selected=true;}else if($4.attributes.getNamedItem('selected')!=null&&$4.attributes.getNamedItem('selected').value==='selected'){$4.removeAttribute('selected');O.selected=false;;}}}else{if(OG.value===value){$2.setAttribute('selected','selected');OG.selected=true;;}else if($2.attributes.getNamedItem('selected')!=null&&$2.attributes.getNamedItem('selected').value==='selected'){$2.removeAttribute('selected');OG.selected=false;;}}}}
DesignerSpace.Lib.Util.selectedValue=function(id){var $0=window.document.getElementById(id);if(E.selectedIndex==-1){return null;}var $1=E.options[E.selectedIndex].value;return $1;}
DesignerSpace.Lib.Util.selectedText=function(id){var $0=window.document.getElementById(id);if(E.selectedIndex==-1){return null;}var $1=E.options[E.selectedIndex].text;return $1;}
DesignerSpace.Lib.Util.setUnChecked=function(Id){if(document.getElementById(Id)==null){return;}document.getElementById ( Id).checked=false;}
DesignerSpace.Lib.Util.registerEvent=function(E,eventName,elementEventListener){DesignerSpace.Lib.Util.registerEvent2(document.getElementById(E),eventName,elementEventListener);}
DesignerSpace.Lib.Util.registerClick=function(id,elementEventListener){DesignerSpace.Lib.Util.registerEvent2(document.getElementById(id),'click',elementEventListener);}
DesignerSpace.Lib.Util.registerClick2=function(Elemes,elementEventListener){var $enum1=ss.IEnumerator.getEnumerator(Elemes);while($enum1.moveNext()){var $0=$enum1.current;DesignerSpace.Lib.Util.registerEvent2(document.getElementById($0),'click',elementEventListener);}}
DesignerSpace.Lib.Util.deRegisterClick=function(id,elementEventListener){DesignerSpace.Lib.Util.$2(document.getElementById(id),'click',elementEventListener);}
DesignerSpace.Lib.Util.registerEvent2=function(E,eventName,elementEventListener){if(E==null){return;}if(E.addEventListener!=null){E.addEventListener(eventName,elementEventListener,false);}else if(E.attachEvent!=null){E.attachEvent('on'+eventName, elementEventListener);}else{E['on'+eventName]= elementEventListener;}}
DesignerSpace.Lib.Util.$2=function($p0,$p1,$p2){if($p0==null){return;}if(E.removeEventListener!=null){$p0.removeEventListener($p1,$p2,false);}else if(E.detachEvent!=null){$p0.detachEvent('on'+$p1, $p2);}else{$p0['on'+$p1]=$p2;}}
DesignerSpace.Lib.Util.findByClass=function(elem,className){var $0=elem.children;for(var $1=0;$1<$0.length;$1++){var $2=$0[$1];if($2.className===className){return $2;}var $3=DesignerSpace.Lib.Util.findByClass($2,className);if($3!=null){return $3;}}return null;}
DesignerSpace.Lib.Util.registerClick3=function(Elem,elementEventListener){DesignerSpace.Lib.Util.registerEvent2(Elem,'click',elementEventListener);}
DesignerSpace.Lib.Util.registerChange=function(E,elementEventListener){DesignerSpace.Lib.Util.registerEvent2(document.getElementById(E),'change',elementEventListener);}
DesignerSpace.Lib.Util.$3=function($p0){$p0.preventDefault();$p0.stopPropagation();$p0.stopImmediatePropagation();}
DesignerSpace.Lib.Util.$4=function($p0){var $0=window.document.getElementById($p0);if($0==null){return;}$0.style.visibility='visible';}
DesignerSpace.Lib.Util.$5=function($p0){var $0=window.document.getElementById($p0);if($0==null){return;}$0.style.display='block';}
DesignerSpace.Lib.Util.$6=function($p0){var $0=window.document.getElementById($p0);if($0==null){return;}$0.style.display='none';}
DesignerSpace.Lib.Util.$7=function($p0){return window.document.getElementById($p0)!=null;}
DesignerSpace.Lib.Util.$8=function($p0,$p1){if(DesignerSpace.Lib.Util.$7($p0)){document.getElementById($p0).className=$p1;}}
DesignerSpace.Lib.Util.$9=function($p0){if(DesignerSpace.Lib.Util.$7($p0)){window.document.getElementById($p0).style.visibility='hidden';}}
DesignerSpace.Lib.Util.scrollTo=function(Id){if(DesignerSpace.Lib.Util.$7(Id)){try{window.document.getElementById(Id).scrollIntoView();}catch($0){}}}
DesignerSpace.Lib.Util.noTags=function(s){return s.toLowerCase().replaceAll('<u>','').replaceAll('</u>','').replaceAll('<b>','').replaceAll('<i>','').replaceAll('</b>','').replaceAll('</i>','');}
DesignerSpace.Lib.Util.setFocus=function(Id){if(document.getElementById(Id)==null){return;}else{document.getElementById(Id).focus();}}
DesignerSpace.Lib.Util.setCheckedValue=function(Id,value){if(value){DesignerSpace.Lib.Util.setChecked(Id);}else{DesignerSpace.Lib.Util.setUnChecked(Id);}}
DesignerSpace.Lib.Util.$A=function($p0,$p1){var $0=0;for(var $1=0;$1<$p0.children.length;$1++){var $2=$p0.children[$1];if(String.isNullOrEmpty($p1)||$p1==='*'){$0++;continue;}if($p1.toLowerCase()===$2.tagName.toLowerCase()){$0++;}}return $0;}
DesignerSpace.Lib.Util.$B=function($p0,$p1,$p2){DesignerSpace.Lib.Util.registerEvent($p0,'mouseenter',$p1);DesignerSpace.Lib.Util.registerEvent($p0,'mouseleave',$p2);}
DesignerSpace.Lib.Util.$C=function($p0){return !document.getElementById($p0).hasAttribute('disabled');}
DesignerSpace.Lib.Util.$D=function($p0){return !DesignerSpace.Lib.Util.$C($p0);}
DesignerSpace.Lib.Util.applyTemplate=function(templateId,Dict){var $0=document.getElementById(templateId).innerHTML;var $1=$0;var $enum1=ss.IEnumerator.getEnumerator(Object.keys(Dict));while($enum1.moveNext()){var $2=$enum1.current;$1=$1.replace(new RegExp('{'+$2+'}','g'),Dict[$2].toString());}return $1;}
DesignerSpace.Lib.Util.setFocusOnEditableChild=function(E){for(var $0=0;$0<E.children.length;$0++){var $1=E.children[$0];switch($1.tagName.toLowerCase()){case 'input':case 'select':DesignerSpace.Lib.Util.setFocus($1.id);return true;default:var $2=DesignerSpace.Lib.Util.setFocusOnEditableChild($1);if($2){return true;}break;}}return false;}
DesignerSpace.Lib.Util.$E=function($p0){if(DesignerSpace.Lib.Util.$7($p0)){DesignerSpace.Lib.Util.setFocusOnEditableChild(document.getElementById($p0));}}
Type.registerNamespace('DesignSpace.Lib');DesignSpace.Lib._Worker=function(){}
DesignSpace.Lib._Worker.$B=function(){DesignSpace.Lib._Worker.$1=function($p1_0){
DesignSpace.Lib._Worker.$16();};DesignSpace.Lib._Worker.$0=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$17($1_0);};DesignSpace.Lib._Worker.$2=function($p1_0){
DesignSpace.Lib._Worker.$15($p1_0,true);};DesignSpace.Lib._Worker.$3=function($p1_0){
DesignSpace.Lib._Worker.$15($p1_0,false);};DesignSpace.Lib._Worker.$4=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);if(DesignerSpace.Lib.Util.isChecked('muteInfo_'+$1_0)){DesignerSpace.Lib.Util.$0('copyInfo_'+$1_0);}else{DesignerSpace.Lib.Util.$1('copyInfo_'+$1_0);}DesignerSpace.Lib.Util.setUnChecked('copyInfo_'+$1_0);};DesignSpace.Lib._Worker.$5=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$12($1_0);};DesignSpace.Lib._Worker.$6=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$10($1_0);};DesignSpace.Lib._Worker.$7=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$F($1_0);};DesignSpace.Lib._Worker.$8=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$D($1_0);};DesignSpace.Lib._Worker.$9=function($p1_0){
var $1_0=DesignSpace.Lib._Worker.$14($p1_0);DesignSpace.Lib._Worker.$C($1_0);};DesignSpace.Lib._Worker.$A=function($p1_0){
DesignSpace.Lib._Worker.$0=null;DesignSpace.Lib._Worker.$1=null;DesignSpace.Lib._Worker.$2=null;DesignSpace.Lib._Worker.$3=null;DesignSpace.Lib._Worker.$4=null;DesignSpace.Lib._Worker.$5=null;DesignSpace.Lib._Worker.$6=null;DesignSpace.Lib._Worker.$7=null;DesignSpace.Lib._Worker.$8=null;DesignSpace.Lib._Worker.$9=null;DesignSpace.Lib._Worker.$A=null;};}
DesignSpace.Lib._Worker.$C=function($p0){DesignerSpace.Lib.Util.registerClick('remove2_'+$p0,DesignSpace.Lib._Worker.$9);var $0=document.getElementById('metric_'+$p0);$0.parentNode.removeChild($0);}
DesignSpace.Lib._Worker.$D=function($p0){var $0=DesignerSpace.Lib.Util.selectedValue('dimension_'+$p0);var $1=DesignerSpace.Lib.Util.selectedText('dimension_'+$p0);var $2=$0+'_'+$p0;var $3='metric_'+$2;if(document.getElementById($3)!=null){DesignerSpace.Lib.Util.$E($3);return;}var $4={};$4['ID']=$p0;$4['value']=$0;$4['text']=$1;var $5=DesignerSpace.Lib.Util.applyTemplate('DimensionTemplate',$4);var $6=document.createElement('li');$6.setAttribute('id',$3);$6.innerHTML=$5;var $7=document.getElementById('metrics_'+$p0);$7.appendChild($6);DesignerSpace.Lib.Util.registerClick('remove2_'+$2,DesignSpace.Lib._Worker.$9);}
DesignSpace.Lib._Worker.$E=function($p0){var $0='metrics_'+$p0;if(DesignerSpace.Lib.Util.$7($0)){var $1=document.getElementById($0);for(var $2=0;$2<$1.children.length;$2++){var $3=$1.children[$2];if($3.tagName.toLowerCase()==='li'){var $4=$3.id.substr($3.id.indexOf('_')+1);DesignerSpace.Lib.Util.deRegisterClick('remove2_'+$4,DesignSpace.Lib._Worker.$9);}}}}
DesignSpace.Lib._Worker.$F=function($p0){DesignSpace.Lib._Worker.$11('copyLib_',$p0);}
DesignSpace.Lib._Worker.$10=function($p0){DesignSpace.Lib._Worker.$11('copyGroups_',$p0);}
DesignSpace.Lib._Worker.$11=function($p0,$p1){if($p1==null){$p1=DesignSpace.Lib._Worker.$13($p0);}if($p1==null){return;}var $0=DesignerSpace.Lib.Util.isChecked($p0+$p1);var $1=document.getElementById('sources');var $2=DesignerSpace.Lib.Util.$A($1,'li');for(var $3=1;$3<=$2;$3++){if($3.toString()===$p1){continue;}if($0){DesignerSpace.Lib.Util.$0($p0+$3);}else{DesignerSpace.Lib.Util.$1($p0+$3);}DesignerSpace.Lib.Util.setUnChecked($p0+$3);}}
DesignSpace.Lib._Worker.$12=function($p0){if($p0==null){$p0=DesignSpace.Lib._Worker.$13('copyInfo_');}if($p0==null){return;}var $0=DesignerSpace.Lib.Util.isChecked('copyInfo_'+$p0);var $1=document.getElementById('sources');var $2=DesignerSpace.Lib.Util.$A($1,'li');for(var $3=1;$3<=$2;$3++){if($3.toString()===$p0){continue;}if($0){DesignerSpace.Lib.Util.$0('copyInfo_'+$3);DesignerSpace.Lib.Util.$1('muteInfo_'+$3);DesignerSpace.Lib.Util.setChecked('muteInfo_'+$3);}else{DesignerSpace.Lib.Util.$1('copyInfo_'+$3);DesignerSpace.Lib.Util.setUnChecked('muteInfo_'+$3);}DesignerSpace.Lib.Util.setUnChecked('copyInfo_'+$3);}}
DesignSpace.Lib._Worker.$13=function($p0){var $0=document.getElementById('sources');var $1=DesignerSpace.Lib.Util.$A($0,'li');for(var $2=1;$2<=$1;$2++){var $3=DesignerSpace.Lib.Util.isChecked($p0+$2)&&DesignerSpace.Lib.Util.$C($p0+$2);if($3){return $2.toString();}}return null;}
DesignSpace.Lib._Worker.$14=function($p0){var $0=($p0.srcElement!=null)?$p0.srcElement:$p0.target;var $1=$0.id;var $2=$1.substr($1.indexOf('_')+1);return $2;}
DesignSpace.Lib._Worker.$15=function($p0,$p1){var $0=DesignSpace.Lib._Worker.$14($p0);if($p1){DesignerSpace.Lib.Util.$4('remove_'+$0);}else{DesignerSpace.Lib.Util.$9('remove_'+$0);}}
DesignSpace.Lib._Worker.$16=function(){var $0=document.getElementById('sources');var $1=DesignerSpace.Lib.Util.$A($0,'li');if(!$1){$1=1;}while(document.getElementById('source_'+$1)!=null){$1=$1+1;}var $2=$1.toString();var $3={};$3['ID']=$2;var $4=DesignerSpace.Lib.Util.applyTemplate('SourceTemplate',$3);var $5=document.createElement('li');$5.innerHTML=$4;$0.appendChild($5);DesignerSpace.Lib.Util.registerClick('remove_'+$2,DesignSpace.Lib._Worker.$0);DesignerSpace.Lib.Util.registerClick('muteInfo_'+$2,DesignSpace.Lib._Worker.$4);DesignerSpace.Lib.Util.registerClick('copyInfo_'+$2,DesignSpace.Lib._Worker.$5);DesignerSpace.Lib.Util.registerClick('copyGroups_'+$2,DesignSpace.Lib._Worker.$6);DesignerSpace.Lib.Util.registerClick('copyLib_'+$2,DesignSpace.Lib._Worker.$7);DesignerSpace.Lib.Util.registerClick('add2_'+$2,DesignSpace.Lib._Worker.$8);DesignSpace.Lib._Worker.$12(null);DesignSpace.Lib._Worker.$10(null);DesignSpace.Lib._Worker.$F(null);DesignerSpace.Lib.Util.setFocus('name_'+$2);}
DesignSpace.Lib._Worker.$17=function($p0){var $0=document.getElementById('sources');var $1=DesignerSpace.Lib.Util.$A($0,'li');if($1===1){DesignSpace.Lib._Worker.$18($p0);return;}var $2=document.getElementById('source_'+$p0);DesignerSpace.Lib.Util.deRegisterClick('remove_'+$p0,DesignSpace.Lib._Worker.$0);DesignerSpace.Lib.Util.deRegisterClick('add_'+$p0,DesignSpace.Lib._Worker.$1);DesignerSpace.Lib.Util.deRegisterClick('muteInfo_'+$p0,DesignSpace.Lib._Worker.$4);DesignerSpace.Lib.Util.deRegisterClick('copyInfo_'+$p0,DesignSpace.Lib._Worker.$5);DesignerSpace.Lib.Util.deRegisterClick('copyGroups_'+$p0,DesignSpace.Lib._Worker.$6);DesignerSpace.Lib.Util.deRegisterClick('copyLib_'+$p0,DesignSpace.Lib._Worker.$7);DesignerSpace.Lib.Util.deRegisterClick('add2_'+$p0,DesignSpace.Lib._Worker.$8);DesignSpace.Lib._Worker.$E($p0);$2.parentNode.parentNode.removeChild($2.parentNode);}
DesignSpace.Lib._Worker.$18=function($p0){}
DesignSpace.Lib._Worker.$19=function(){DesignerSpace.Lib.Util.registerClick('add',DesignSpace.Lib._Worker.$1);DesignSpace.Lib._Worker.$16();}
DesignSpace.Canvas.registerClass('DesignSpace.Canvas');DesignerSpace.Lib.Events.registerClass('DesignerSpace.Lib.Events');DesignerSpace.Lib.Util.registerClass('DesignerSpace.Lib.Util');DesignSpace.Lib._Worker.registerClass('DesignSpace.Lib._Worker');DesignerSpace.Lib.Events.click='click';DesignerSpace.Lib.Events.change='change';DesignSpace.Lib._Worker.$0=null;DesignSpace.Lib._Worker.$1=null;DesignSpace.Lib._Worker.$2=null;DesignSpace.Lib._Worker.$3=null;DesignSpace.Lib._Worker.$4=null;DesignSpace.Lib._Worker.$5=null;DesignSpace.Lib._Worker.$6=null;DesignSpace.Lib._Worker.$7=null;DesignSpace.Lib._Worker.$8=null;DesignSpace.Lib._Worker.$9=null;DesignSpace.Lib._Worker.$A=null;