#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
echo ...................
echo RoboFab module installs with relative path so needs to be re-installed after Post Deployment
echo Keeping all dependent Modules under libs directory.
echo " '$OPENSHIFT_HOMEDIR/app-deployments/current/repo/libs/robofab-ufo3k/install.py'"
echo "Executing 'python $OPENSHIFT_HOMEDIR/app-deployments/current/repo/libs/robofab-ufo3k/install.py'"
python $OPENSHIFT_HOMEDIR/app-deployments/current/repo/libs/robofab-ufo3k/install.py