#!/bin/bash
LAST_RUN=last_hourly_cron_ran
date > $OPENSHIFT_DATA_DIR$LAST_RUN

CRON_HOUR=cron_hour.txt
UPLOAD=uploads
OPENSHIFT_UPLOAD_DIR=$OPENSHIFT_DATA_DIR$UPLOAD
CRON_LOG_FILE=$OPENSHIFT_DATA_DIR$CRON_HOUR

cd $OPENSHIFT_DATA_DIR$UPLOAD
echo "Running Hourly Cron job Last update on 19-Jul-15 01:43 HRS IST" >$CRON_LOG_FILE
date >>$CRON_LOG_FILE
echo "Job Started ">>$CRON_LOG_FILE
echo $OPENSHIFT_UPLOAD_DIR >>$CRON_LOG_FILE
echo "List of Files being deleted">>$CRON_LOG_FILE
find $OPENSHIFT_UPLOAD_DIR -name '*.*' -type f -mmin +360 >>$CRON_LOG_FILE
find $OPENSHIFT_UPLOAD_DIR -name '*.*' -type f -mmin +360 -delete
echo "List of Empty Directories being deleted">>$CRON_LOG_FILE
find $OPENSHIFT_UPLOAD_DIR -empty -type d >>$CRON_LOG_FILE
find $OPENSHIFT_UPLOAD_DIR -empty -type d -delete
echo "Job finished" >>$CRON_LOG_FILE

#Quota Calculations
QUOTA_FILE=quota.txt
QUOTA_LOG_FILE=$OPENSHIFT_DATA_DIR$QUOTA_FILE
function get_used_space() {
  echo $(quota -w|egrep -v '(quotas|Filesystem)'|awk -F ' ' '{ print $2}')
}

# returns the total quota for your gear
function get_quota() {
  echo $(quota -w|egrep -v '(quotas|Filesystem)'|awk -F ' ' '{ print $4}')
}

used_space=$(get_used_space)
quota=$(get_quota)
percentage=$(echo "(${used_space}/${quota})*100" |bc -l|sed 's/^\./0./')
current_usage=${percentage/\.*}
echo " "$(date)>$QUOTA_LOG_FILE
echo " Current gear storage usage is ${current_usage}%">>$QUOTA_LOG_FILE
echo " Current gear storage usage is ${used_space}">>$QUOTA_LOG_FILE

# Above Quota code was originally created by Marek Mahut <mmahut@redhat.com>
# https://github.com/mmahut/openshift-quota-monitor-cartridge/blob/master/lib/functions